---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/light-stemcell-builder

inputs:
  - name: builder-src
  - name: stemcell

outputs:
  - name: light-stemcell
  - name: raw-stemcell

run:
  path: builder-src/ci/tasks/build-light-stemcell.sh

params:
  BUCKET_NAME:         ""
  BOSH_IO_BUCKET_NAME: ""
