---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release

inputs:
  - name: bosh-cli
  - name: bosh-cpi-release
  - name: builder-src
  - name: light-stemcell
  - name: terraform

outputs:
  - name: deployment-state

run:
  path: builder-src/ci/tasks/deploy-skeletal.sh

params:
  SSH_PRIVATE_KEY:      ""
  GCE_CREDENTIALS_JSON: ""
